/** @type {import("jest").Config} */
module.exports = {
  preset: "ts-jest",
  testEnvironment: "jsdom",
  coverageProvider: "v8",
  roots: ["<rootDir>/src"],
  testMatch: ["**/*.test.ts"],
  clearMocks: true,
  moduleNameMapper: {
    "\\.module\\.css$": "identity-obj-proxy",
    "\\.css$": "identity-obj-proxy",
    "^@/(.*)$": "<rootDir>/src/$1",
  },
  collectCoverageFrom: [
    "src/shared/utils/apiErrors.ts",
    "src/shared/utils/parseApiDateTime.ts",
    "src/shared/utils/applicationApplyBlock.ts",
    "src/shared/utils/personDisplayName.ts",
    "src/shared/utils/applicationStatus.ts",
    "src/shared/utils/avatarUtils.ts",
    "src/shared/utils/cropAvatar.ts",
    "src/shared/utils/applicationFormat.ts",
    "src/shared/utils/vietnamTime.ts",
    "src/shared/utils/courseLecturer.ts",
    "src/shared/utils/messageReactions.ts",
    "src/shared/utils/correspondencePolicy.ts",
    "src/shared/utils/correspondenceMessages.ts",
    "src/shared/utils/applicationTimeline.ts",
    "src/shared/utils/applicationProcessFlow.ts",
    "src/shared/utils/lecturerProcessFlow.ts",
    "src/modules/auth/utils/authValidation.utils.ts",
    "src/modules/tutor/utils/skillOptions.ts",
    "src/modules/tutor/utils/tutorCourseAvailability.ts",
    "src/modules/lecturer/utils/lecturerValidation.utils.ts",
  ],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov", "json-summary"],
};
