import type { ApplicationScenario } from "./seedInteractions";

export const WAVE_2_APPLICATION_SCENARIOS: ApplicationScenario[] = [
    {
        candidateEmail: "zoe.hayes@candidate.edu.au",
        courseCode: "LAWS1001",
        roleName: "tutor",
        availability: "Part Time",
        skills: "Case briefing, legal research, moot coaching",
        experience: "Law society moot court semi-finalist.",
        motivation:
            "I want to help first-year students read cases critically and structure arguments clearly.",
        appliedDaysAgo: 10,
        steps: [
            {
                kind: "lecturer_message",
                lecturerEmail: "hannah.walsh@lecturer.edu.au",
                body: "Strong moot background. Which tutorial stream can you cover?",
            },
            {
                kind: "candidate_message",
                body: "I can take the Wednesday 10am stream and Friday revision clinic.",
                replyToLecturer: true,
            },
            { kind: "shortlist_and_rank", lecturerEmail: "hannah.walsh@lecturer.edu.au" },
        ],
    },
    {
        candidateEmail: "ryan.obrien@candidate.edu.au",
        courseCode: "LAWS1001",
        roleName: "tutor",
        availability: "Full Time",
        skills: "Statutory interpretation, essay feedback, debate facilitation",
        experience: "Peer mentor in constitutional law.",
        motivation: "Tutorial facilitation is the best way I can support new law students.",
        appliedDaysAgo: 7,
        steps: [
            {
                kind: "lecturer_message",
                lecturerEmail: "elena.voss@lecturer.edu.au",
                body: "Please confirm you are comfortable marking short problem questions.",
            },
            { kind: "shortlist_and_rank", lecturerEmail: "elena.voss@lecturer.edu.au" },
            { kind: "select", lecturerEmail: "elena.voss@lecturer.edu.au" },
            { kind: "offer_accept" },
        ],
    },
    {
        candidateEmail: "ethan.brooks@candidate.edu.au",
        courseCode: "COSC2758",
        roleName: "tutor",
        availability: "Part Time",
        skills: "JavaScript, REST APIs, testing, code review",
        experience: "Open-source contributor on a student scheduling app.",
        motivation: "I enjoy pairing with students who are debugging their first full-stack feature.",
        appliedDaysAgo: 5,
        steps: [
            {
                kind: "lecturer_message",
                lecturerEmail: "jane.morrison@lecturer.edu.au",
                body: "Can you run a clinic on API integration testing?",
            },
            {
                kind: "candidate_message",
                body: "Yes — I use Jest and Supertest in my current project and can demo both.",
                replyToLecturer: true,
            },
            { kind: "react_last_lecturer", by: "candidate", emoji: "👏" },
            { kind: "shortlist_and_rank", lecturerEmail: "jane.morrison@lecturer.edu.au" },
        ],
    },
    {
        candidateEmail: "lucas.mueller@candidate.edu.au",
        courseCode: "COSC2758",
        roleName: "lab_assistant",
        availability: "Part Time",
        skills: "PostgreSQL, migrations, backend deployment",
        experience: "Database administrator intern.",
        motivation: "Lab support for schema design exercises is my strongest area.",
        appliedDaysAgo: 4,
        steps: [],
    },
    {
        candidateEmail: "priya.nair@candidate.edu.au",
        courseCode: "BIOL1001",
        roleName: "lab_assistant",
        availability: "Part Time",
        skills: "Microscopy, sterile technique, lab notebook coaching",
        experience: "Undergraduate research assistant in a cell culture lab.",
        motivation: "I can guide students through microscopy practicals with patience and precision.",
        appliedDaysAgo: 9,
        steps: [
            {
                kind: "lecturer_message",
                lecturerEmail: "tomas.rivera@lecturer.edu.au",
                body: "Have you completed biosafety induction for teaching labs?",
            },
            {
                kind: "candidate_message",
                body: "Yes — BSL-1 and chemical hygiene completed last semester.",
                replyToLecturer: true,
            },
            { kind: "shortlist_and_rank", lecturerEmail: "tomas.rivera@lecturer.edu.au" },
            { kind: "select", lecturerEmail: "tomas.rivera@lecturer.edu.au" },
            { kind: "offer_accept" },
        ],
    },
    {
        candidateEmail: "hannah.choi@candidate.edu.au",
        courseCode: "BIOL1001",
        roleName: "tutor",
        availability: "Part Time",
        skills: "Genetics problem sets, diagram explanation, exam revision",
        experience: "Supplementary instruction leader for introductory biology.",
        motivation: "I want to make genetics tutorials less intimidating for first-year students.",
        appliedDaysAgo: 11,
        steps: [
            {
                kind: "lecturer_message",
                lecturerEmail: "rachel.okonkwo@lecturer.edu.au",
                body: "Could you cover Mendelian genetics tutorials in week 4?",
            },
        ],
    },
    {
        candidateEmail: "sofia.rossi@candidate.edu.au",
        courseCode: "CHEM1011",
        roleName: "lab_assistant",
        availability: "Full Time",
        skills: "Titration, spectroscopy, lab safety, waste disposal",
        experience: "Chemistry peer tutor for two years.",
        motivation: "General chemistry labs need assistants who can troubleshoot equipment calmly.",
        appliedDaysAgo: 6,
        steps: [
            {
                kind: "lecturer_message",
                lecturerEmail: "yuki.nakamura@lecturer.edu.au",
                body: "Your titration experience is relevant. Are evenings available?",
            },
            {
                kind: "candidate_message",
                body: "Tuesday and Thursday 5–8pm work well for me.",
                replyToLecturer: true,
            },
            { kind: "react_last_candidate", by: "lecturer", emoji: "👍" },
        ],
    },
    {
        candidateEmail: "noah.park@candidate.edu.au",
        courseCode: "STAT1371",
        roleName: "tutor",
        availability: "Part Time",
        skills: "R, hypothesis testing, regression, data visualisation",
        experience: "Statistics learning centre tutor.",
        motivation: "Students often struggle with interpreting p-values — I can help with that.",
        appliedDaysAgo: 8,
        steps: [
            {
                kind: "lecturer_message",
                lecturerEmail: "yuki.nakamura@lecturer.edu.au",
                body: "Please outline how you would teach confidence intervals intuitively.",
            },
            {
                kind: "candidate_message",
                body: "I start with bootstrap resampling on a small dataset before introducing the formula.",
                replyToLecturer: true,
            },
            { kind: "shortlist_and_rank", lecturerEmail: "yuki.nakamura@lecturer.edu.au" },
        ],
    },
    {
        candidateEmail: "grace.adeyemi@candidate.edu.au",
        courseCode: "STAT1371",
        roleName: "lab_assistant",
        availability: "Part Time",
        skills: "Python, pandas, Jupyter, assignment troubleshooting",
        experience: "Data science bootcamp teaching assistant.",
        motivation: "Computing labs are where students need the most hands-on support.",
        appliedDaysAgo: 3,
        steps: [],
    },
    {
        candidateEmail: "zoe.hayes@candidate.edu.au",
        courseCode: "MARK1001",
        roleName: "tutor",
        availability: "Part Time",
        skills: "Consumer insights, survey design, workshop facilitation",
        experience: "Market research intern at a regional agency.",
        motivation: "I can help students turn survey data into actionable campaign insights.",
        appliedDaysAgo: 14,
        steps: [
            {
                kind: "lecturer_message",
                lecturerEmail: "elena.voss@lecturer.edu.au",
                body: "We are finalising the tutor roster. I will update you by Friday.",
            },
        ],
    },
    {
        candidateEmail: "grace.adeyemi@candidate.edu.au",
        courseCode: "COMP9417",
        roleName: "tutor",
        availability: "Part Time",
        skills: "Feature engineering, model interpretability, scikit-learn",
        experience: "Kaggle notebooks contributor.",
        motivation: "I enjoy teaching students how to diagnose overfitting in practical labs.",
        appliedDaysAgo: 12,
        steps: [
            {
                kind: "lecturer_message",
                lecturerEmail: "wei.zhang@lecturer.edu.au",
                body: "Share an example of explaining SHAP values to beginners.",
            },
            {
                kind: "candidate_message",
                body: "I use a small housing dataset and compare global vs local explanations on the board.",
                replyToLecturer: true,
            },
            { kind: "shortlist_and_rank", lecturerEmail: "wei.zhang@lecturer.edu.au" },
        ],
    },
    {
        candidateEmail: "ethan.brooks@candidate.edu.au",
        courseCode: "INTE2400",
        roleName: "lab_assistant",
        availability: "Part Time",
        skills: "Cisco Packet Tracer, VLANs, ACL troubleshooting",
        experience: "Campus network operations volunteer.",
        motivation: "Network labs benefit from assistants who can debug configs quickly.",
        appliedDaysAgo: 2,
        steps: [],
    },
    {
        candidateEmail: "lucas.mueller@candidate.edu.au",
        courseCode: "ISYS9001",
        roleName: "tutor",
        availability: "Part Time",
        skills: "SAP navigation, business process documentation",
        experience: "ERP implementation project team member.",
        motivation: "Enterprise systems tutorials need tutors who understand real workflows.",
        appliedDaysAgo: 16,
        steps: [
            {
                kind: "lecturer_message",
                lecturerEmail: "marcus.chen@lecturer.edu.au",
                body: "Thank you for applying. The tutorial team is already staffed this term.",
            },
            { kind: "reject", lecturerEmail: "marcus.chen@lecturer.edu.au" },
        ],
    },
    {
        candidateEmail: "noah.park@candidate.edu.au",
        courseCode: "MATH1131",
        roleName: "tutor",
        availability: "Part Time",
        skills: "Calculus workshops, integration techniques, exam prep",
        experience: "Mathematics tutoring for three semesters.",
        motivation: "Weekly problem sessions are where I can help students build fluency.",
        appliedDaysAgo: 13,
        steps: [
            {
                kind: "lecturer_message",
                lecturerEmail: "priya.sharma@lecturer.edu.au",
                body: "Can you cover the integration techniques workshop?",
            },
            { kind: "shortlist_and_rank", lecturerEmail: "priya.sharma@lecturer.edu.au" },
            { kind: "select", lecturerEmail: "priya.sharma@lecturer.edu.au" },
            { kind: "offer_decline" },
        ],
    },
    {
        candidateEmail: "priya.nair@candidate.edu.au",
        courseCode: "PHYS1161",
        roleName: "tutor",
        availability: "Part Time",
        skills: "Mechanics problem solving, whiteboard coaching",
        experience: "Physics help desk volunteer.",
        motivation: "Mechanics tutorials are my favourite sessions to facilitate.",
        appliedDaysAgo: 4,
        steps: [],
    },
    {
        candidateEmail: "ryan.obrien@candidate.edu.au",
        courseCode: "ENGG1300",
        roleName: "tutor",
        availability: "Part Time",
        skills: "Team charters, design reviews, technical writing",
        experience: "Engineering project manager on a capstone team.",
        motivation: "Studio tutorials need facilitators who can coach teamwork dynamics.",
        appliedDaysAgo: 6,
        steps: [
            {
                kind: "lecturer_message",
                lecturerEmail: "rachel.okonkwo@lecturer.edu.au",
                body: "How would you run a retrospective after a failed prototype test?",
            },
            {
                kind: "candidate_message",
                body: "I use a blameless format: facts, hypotheses, and one concrete next experiment.",
                replyToLecturer: true,
            },
        ],
    },
    {
        candidateEmail: "hannah.choi@candidate.edu.au",
        courseCode: "ACCT5001",
        roleName: "tutor",
        availability: "Part Time",
        skills: "IFRS basics, consolidation exercises, case discussion",
        experience: "Accounting honours student.",
        motivation: "Postgraduate accounting students need structured revision tutorials.",
        appliedDaysAgo: 18,
        steps: [],
    },
    {
        candidateEmail: "sofia.rossi@candidate.edu.au",
        courseCode: "COMP9001",
        roleName: "tutor",
        availability: "Part Time",
        skills: "Literature reviews, citation management, research ethics",
        experience: "Graduate research methods workshop assistant.",
        motivation: "I can support students writing their first thesis proposal.",
        appliedDaysAgo: 15,
        steps: [
            {
                kind: "lecturer_message",
                lecturerEmail: "wei.zhang@lecturer.edu.au",
                body: "Please confirm availability for the ethics module tutorial.",
            },
        ],
    },
    {
        candidateEmail: "alex.nguyen@candidate.edu.au",
        courseCode: "STAT1371",
        roleName: "lab_assistant",
        availability: "Part Time",
        skills: "Python, NumPy, lab debugging",
        experience: "Data science club mentor.",
        motivation: "I want to help students complete statistics computing labs confidently.",
        appliedDaysAgo: 1,
        steps: [
            {
                kind: "lecturer_message",
                lecturerEmail: "marcus.chen@lecturer.edu.au",
                body: "Welcome — please introduce yourself in the correspondence thread when ready.",
            },
        ],
    },
    {
        candidateEmail: "samira.patel@candidate.edu.au",
        courseCode: "CHEM1011",
        roleName: "tutor",
        availability: "Part Time",
        skills: "Stoichiometry workshops, exam revision, problem sets",
        experience: "Chemistry supplemental instruction leader.",
        motivation: "Stoichiometry is a hurdle for many students — I can run focused clinics.",
        appliedDaysAgo: 5,
        steps: [
            {
                kind: "lecturer_message",
                lecturerEmail: "yuki.nakamura@lecturer.edu.au",
                body: "Could you run a pre-exam stoichiometry revision session?",
            },
            { kind: "shortlist_and_rank", lecturerEmail: "yuki.nakamura@lecturer.edu.au" },
        ],
    },
    {
        candidateEmail: "mia.tan@candidate.edu.au",
        courseCode: "LAWS1001",
        roleName: "tutor",
        availability: "Part Time",
        skills: "Legal writing, IRAC structure, peer review",
        experience: "Editor on the student law review.",
        motivation: "Clear legal writing is a skill I enjoy teaching in small groups.",
        appliedDaysAgo: 8,
        steps: [
            {
                kind: "lecturer_message",
                lecturerEmail: "hannah.walsh@lecturer.edu.au",
                body: "Your writing background is useful. Are you free for evening tutorials?",
            },
            {
                kind: "candidate_message",
                body: "Mondays and Wednesdays after 6pm work for me.",
                replyToLecturer: true,
            },
        ],
    },
    {
        candidateEmail: "james.oconnor@candidate.edu.au",
        courseCode: "STAT1371",
        roleName: "tutor",
        availability: "Part Time",
        skills: "Probability, combinatorics, worked examples",
        experience: "High school mathematics tutor transitioning to university stats.",
        motivation: "Probability intuition is best built through guided examples.",
        appliedDaysAgo: 17,
        steps: [
            {
                kind: "lecturer_message",
                lecturerEmail: "yuki.nakamura@lecturer.edu.au",
                body: "We have filled the tutor positions for this intake.",
            },
            { kind: "reject", lecturerEmail: "yuki.nakamura@lecturer.edu.au" },
        ],
    },
    {
        candidateEmail: "chloe.martin@candidate.edu.au",
        courseCode: "BIOL1001",
        roleName: "lab_assistant",
        availability: "Part Time",
        skills: "Gel electrophoresis, pipetting workshops, safety briefings",
        experience: "Biology lab demonstrator.",
        motivation: "Hands-on lab technique coaching is where I add the most value.",
        appliedDaysAgo: 7,
        steps: [
            {
                kind: "lecturer_message",
                lecturerEmail: "tomas.rivera@lecturer.edu.au",
                body: "Please confirm you can attend the lab assistant induction next week.",
            },
            {
                kind: "candidate_message",
                body: "I will be there — I have my lab coat and safety glasses ready.",
                replyToLecturer: true,
            },
            { kind: "react_last_lecturer", by: "candidate", emoji: "❤️" },
        ],
    },
    {
        candidateEmail: "daniel.kim@candidate.edu.au",
        courseCode: "COSC2123",
        roleName: "tutor",
        availability: "Part Time",
        skills: "Graph algorithms, dynamic programming, contest problems",
        experience: "ICPC regional contest participant.",
        motivation: "Algorithm tutorials should balance rigour with approachable examples.",
        appliedDaysAgo: 9,
        steps: [
            {
                kind: "lecturer_message",
                lecturerEmail: "noah.fischer@lecturer.edu.au",
                body: "How would you introduce Dijkstra's algorithm in 50 minutes?",
            },
            {
                kind: "candidate_message",
                body: "Motivate with a map routing example, then build the priority queue step by step.",
                replyToLecturer: true,
            },
            { kind: "shortlist_and_rank", lecturerEmail: "noah.fischer@lecturer.edu.au" },
        ],
    },
    {
        candidateEmail: "aisha.rahman@candidate.edu.au",
        courseCode: "CHEM1011",
        roleName: "tutor",
        availability: "Part Time",
        skills: "Balancing equations, mole calculations, exam strategies",
        experience: "Peer-assisted study sessions leader.",
        motivation: "I want to help students build confidence before the mid-semester test.",
        appliedDaysAgo: 2,
        steps: [],
    },
    {
        candidateEmail: "liam.carter@candidate.edu.au",
        courseCode: "LAWS1001",
        roleName: "tutor",
        availability: "Part Time",
        skills: "Tutorial planning, reading guides, formative quizzes",
        experience: "Education minor with law breadth studies.",
        motivation: "I enjoy designing short activities that check understanding.",
        appliedDaysAgo: 20,
        steps: [],
    },
    {
        candidateEmail: "oscar.silva@candidate.edu.au",
        courseCode: "STAT1371",
        roleName: "lab_assistant",
        availability: "Part Time",
        skills: "R Markdown, ggplot2, reproducible workflows",
        experience: "Research methods tutor.",
        motivation: "Reproducible analysis is a habit I want to instil early.",
        appliedDaysAgo: 6,
        steps: [
            {
                kind: "lecturer_message",
                lecturerEmail: "marcus.chen@lecturer.edu.au",
                body: "Can you support the R Markdown troubleshooting desk?",
            },
        ],
    },
];
